apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - account-deployment.yaml
  - customer-deployment.yaml
  - notification-deployment.yaml
  - transaction-deployment.yaml
